service: linebot-openai

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:*'
          Resource: '*'
  environment:
    DYNAMODB_TABLE_NAME: linebot-openai-table-${self:provider.stage}

functions:
  linebotOpenAi:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: POST
    environment:
      LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET}
      LINE_CHANNEL_ACCESS_TOKEN: ${env:LINE_CHANNEL_ACCESS_TOKEN}
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}
      DYNAMODB_TABLE_NAME: ${self:provider.environment.DYNAMODB_TABLE_NAME}

resources:
  Resources:
    linebotOpenAiDb:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: lineUserId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: byLineUserId
            KeySchema:
              - AttributeName: lineUserId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

package:
  exclude:
    - ./**
  include:
    - dist/**
    - node_modules/**
